/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.samantha.proyectofinal;

/**
 *
 * @author huchi
 */
public class Main extends javax.swing.JFrame {

    CredencialPerro Mascota = new CredencialPerro();

    /**
     * Creates new form InicioVentana
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        GenerarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        NamePersonaTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        DireccionTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        NombreMascotaTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        RazaTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ColorTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        HobbiesTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        EdadTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        SexoComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto final | Credenciales");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(102, 102, 102));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Generación de credenciales para Mascotas");
        titleLabel.setToolTipText("");
        getContentPane().add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 604, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 598, -1));

        GenerarButton.setBackground(new java.awt.Color(250, 237, 205));
        GenerarButton.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        GenerarButton.setForeground(new java.awt.Color(0, 0, 0));
        GenerarButton.setText("Generar Credencial");
        GenerarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(GenerarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 592, 92));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText(" Nombre del Dueño");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 260, 30));

        NamePersonaTextField.setBackground(new java.awt.Color(212, 163, 115));
        NamePersonaTextField.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(NamePersonaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 263, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText(" Dirección");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));

        DireccionTextField.setBackground(new java.awt.Color(212, 163, 115));
        DireccionTextField.setForeground(new java.awt.Color(0, 0, 0));
        DireccionTextField.setToolTipText("");
        getContentPane().add(DireccionTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 311, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText(" Nombre de la Mascota");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        NombreMascotaTextField.setBackground(new java.awt.Color(212, 163, 115));
        NombreMascotaTextField.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(NombreMascotaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 260, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText(" Raza");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        RazaTextField.setBackground(new java.awt.Color(212, 163, 115));
        RazaTextField.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(RazaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 260, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText(" Color");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        ColorTextField.setBackground(new java.awt.Color(212, 163, 115));
        ColorTextField.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(ColorTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 310, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText(" Hobbies");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        HobbiesTextField.setBackground(new java.awt.Color(212, 163, 115));
        HobbiesTextField.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(HobbiesTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 263, -1));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText(" Edad");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, -1, -1));

        EdadTextField.setBackground(new java.awt.Color(212, 163, 115));
        EdadTextField.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(EdadTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 310, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText(" Sexo");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        SexoComboBox.setBackground(new java.awt.Color(212, 163, 115));
        SexoComboBox.setForeground(new java.awt.Color(0, 0, 0));
        SexoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Macho", "Hembra", "Otro" }));
        SexoComboBox.setBorder(null);
        getContentPane().add(SexoComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 310, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\huchi\\OneDrive\\Documentos\\NetBeansProjects\\ProyectoFinal\\src\\main\\java\\images\\background.jpg")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GenerarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarButtonActionPerformed
        Mascota.setNombrePersona(NamePersonaTextField.getText());
        Mascota.setDireccion(DireccionTextField.getText());
        Mascota.setNombre(NombreMascotaTextField.getText());
        Mascota.setRaza(RazaTextField.getText());
        Mascota.setColor(ColorTextField.getText());
        Mascota.setHobbies(HobbiesTextField.getText());
        Mascota.setEdad(Integer.parseInt(EdadTextField.getText()));
        Mascota.setSexo(SexoComboBox.getSelectedItem().toString());
        System.out.println(Mascota.toString());

        new CredencialUI(Mascota).setVisible(true);
    }//GEN-LAST:event_GenerarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ColorTextField;
    private javax.swing.JTextField DireccionTextField;
    private javax.swing.JTextField EdadTextField;
    private javax.swing.JButton GenerarButton;
    private javax.swing.JTextField HobbiesTextField;
    private javax.swing.JTextField NamePersonaTextField;
    private javax.swing.JTextField NombreMascotaTextField;
    private javax.swing.JTextField RazaTextField;
    private javax.swing.JComboBox<String> SexoComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
